### ISSUE TITLE
cflinuxfs2-rootfs.trusted_certs should accept an array

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/cflinuxfs2-release#3]
For consistency with other parts of cf like the diego [rep](https://github.com/cloudfoundry/diego-release/blob/develop/jobs/rep/spec#L294-L311), the `trusted_certs` property should accept an array. It's also easier to manipulate arrays with tools like `bosh-cli` than concatenating strings.

cc @wjwoodson

**Comment by sclevine** [comment]
@dgodd

**Comment by dgodd** [comment]
@sclevine I leave this one for you. Is that normal across CF?

**Comment by chhhavi** [comment]
This work looks completed, closing.
